---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: fix-encoding-pragma

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.3
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: https://github.com/mpalmer/action-validator
    rev: v0.5.3
    hooks:
      - id: action-validator
        stages:
          - commit-msg

...
