---

# Documentation References:
# - Creating a Composite Action: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# - Metadata Syntax for Inputs: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
# - Runs for Composite Actions: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-run-steps-actions
# - Composer CLI Documentation: https://getcomposer.org/doc/03-cli.md#install-i
# - Other Implementations: https://github.com/ergebnis/.github/blob/main/actions

name: 📥 Composer install
description: Installs dependencies with composer

inputs:
  dependencies:
    default: locked
    description: 'Which dependencies to install, one of "lowest", "locked", "highest"'
    required: true
  working-directory:
    default: "."
    description: 'Which directory to use as working directory'
    required: true

runs:
  using: 'composite'

  steps:
    - name: 📥 Install ${{ inputs.dependencies }} dependencies with composer
      env:
        COMPOSER_INSTALL_DEPENDENCIES: ${{ inputs.dependencies }}
        COMPOSER_INSTALL_WORKING_DIRECTORY: ${{ inputs.working-directory }}
      run: ${{ github.action_path }}/run.sh
      shell: bash

...
