---

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      os:
        description: The operating system to run the workflow on
        required: true
        type: string
        default: ubuntu-latest
      severity:
        description: Severity level for shell-check
        required: false
        type: string
        default: warning
    secrets:
      token:
        description: Github token used to run this workflow
        required: true

name: 🐞 Differential shell-check

jobs:
  shellcheck:
    runs-on: ${{ inputs.os }}
    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐞 Differential shell-check
        uses: redhat-plumbers-in-action/differential-shellcheck@v4
        with:
          severity: ${{ inputs.severity }}
          token: ${{ secrets.token }}

...
